apps:
  - script : ./server_intrusion.py
    name   : 'intrusion_production_30003'
#    interpreter: /home/gg_greenlab/anaconda3/envs/openmmlab/bin/python
    interpreter: /home/oryza/miniconda3/envs/loitering_envs/bin/python
    args: ".env_production"
  - script: ./run_api_loop_intrusion.py
    name: 'run_api_loop_intrusion'
    interpreter: /home/oryza/miniconda3/envs/head_body_envs/bin/python

